name: core-CI-build

on:
  push:
  workflow_dispatch:

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: main
      - uses: actions/checkout@v3
        with:
          repository: apxxxxxxe/Bouyomi-core
          path: core
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: build
        working-directory: core
        run: |
          GOOS=windows GOARCH=amd64 go build -ldflags "-H windowsgui" -o ../main/core.exe
      - name: git-commit
        working-directory: main
        run: |
          git config --local user.email "calcium629@gmail.com"
          git config --local user.name "apxxxxxxe"
          git add .
          git commit -m "core.exe fix" -a
          git pull
          git push origin $(git symbolic-ref --short HEAD)
