name: core-CI-build

on:
  push:
  workflow_dispatch:

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: build
        run: |
          cd Bouyomi-core
          GOOS=windows GOARCH=amd64 go build -ldflags "-H windowsgui" -o ../core.exe
      - name: git-commit
        run: |
          git config --local user.email "calcium629@gmail.com"
          git config --local user.name "apxxxxxxe"
          git add .
          git commit -m "core.exe fix" -a
          git pull
          git push origin $(git symbolic-ref --short HEAD)
