name: md5-CI-build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    if: ${{ !startsWith(github.ref, 'refs/tags/') }}
    runs-on: windows-latest
    steps:
    - name: disable auto crlf
      uses: steve02081504/disable-autocrlf@v1
    - name: checkout
      uses: actions/checkout@v2
    - name: updates build
      uses: Taromati2/ukagaka-mirror-md5-CI-build@v1
      with:
        build-mode: other
